database:
  host: database.otaku-shelter.ru
  port: 5432
  database: manga
  userid: manga
  password: manga
  migrationstable: migrations
  
secret: secretsecretsecretsecretsecret
issuer: otakushelter.issuer
audience: otakushelter.audience