os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

addons:
  apt:
    packages:
    - sshpass
    
script:
- docker build -t otakushelter/mangas:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Mangas.Web/Dockerfile .
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/mangas:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
    "cd /root/OtakuShelter.Infrastructure/src && \
    ansible-playbook deploy.yml \
    -e \"\
    otakushelter_hosts=mangas \
    otakushelter_port=4001 \
    otakushelter_image=otakushelter/mangas \
    otakushelter_server_name=mangas.staging.otaku-shelter.ru \
    otakushelter_build_number=$TRAVIS_BUILD_NUMBER \
    otakushelter_database_password=$OTAKUSHELTER_DATABASE_PASSWORD \
    otakushelter_rabbitmq_password=$OTAKUSHELTER_RABBITMQ_PASSWORD \
    otakushelter_jwt_secret=$OTAKUSHELTER_JWT_SECRET\" \
    -i inventories/staging"

- docker build -t otakushelter/parsers:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Mangas.Parser/Dockerfile .
- docker push otakushelter/parsers:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
    "cd /root/OtakuShelter.Infrastructure/src && \
    ansible-playbook deploy.yml \
    -e \"\
    otakushelter_hosts=parsers \
    otakushelter_port=4007 \
    otakushelter_image=otakushelter/parsers \
    otakushelter_build_number=$TRAVIS_BUILD_NUMBER \
    otakushelter_database_password=$OTAKUSHELTER_DATABASE_PASSWORD \
    -i inventories/staging"