os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

addons:
  apt:
    packages:
    - sshpass
    
script:
- docker build -t otakushelter/manga:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Manga.Web/Dockerfile .
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/manga:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
    "cd /root/OtakuShelter.Infrastructure/src && \
    ansible-playbook deploy.yml \
    -e \"\
    otakushelter_hosts=mangas \
    otakushelter_nginx_server_name=manga.otaku-shelter.ru \
    otakushelter_nginx_proxy_pass=http://localhost:4001 \
    otakushelter_nginx_config=manga \
    otakushelter_container=otakushelter_manga \
    otakushelter_image=otakushelter/manga \
    otakushelter_port=4001 \
    otakushelter_build_number=$TRAVIS_BUILD_NUMBER \
    otakushelter_database_password=$OTAKUSHELTER_DATABASE_PASSWORD \
    otakushelter_rabbitmq_password=$OTAKUSHELTER_RABBITMQ_PASSWORD \
    otakushelter_secret=$OTAKUSHELTER_SECRET\" \
    -i inventories/staging"