language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
install:
- dotnet restore
script:
- docker-compose build
- docker login -u $OTAKUSHELTER_USERNAME -p $OTAKUSHELTER_PASSWORD
- docker tag otaku-shelter.manga:1.0.$TRAVIS_BUILD_NUMBER otakushelter/otaku-shelter.manga:1.0.$TRAVIS_BUILD_NUMBER
- docker push otakushelter/otaku-shelter.manga:1.0.$TRAVIS_BUILD_NUMBER
- apt-get install sshpass
- ./deploy.sh | sshpass -p $MANGA_PASSWORD ssh $MANGA_USERNAME@MANGA_HOSTNAME "bash"