version: '3.1'
services:
  manga-service:
    image: "otakushelter/manga:1.0.${TRAVIS_BUILD_NUMBER}"
    build:
      context: .
      dockerfile: src/OtakuShelter.Manga.Web/Dockerfile
    ports:
    - 80:80