// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtakuShelter.Manga;

namespace OtakuShelter.Manga.Migrations
{
    [DbContext(typeof(MangaContext))]
    [Migration("20190205231746_Fix1")]
    partial class Fix1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OtakuShelter.Manga.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("MangaId")
                        .HasColumnName("manga_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UploadDate")
                        .HasColumnName("upload_date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("chapters");
                });

            modelBuilder.Entity("OtakuShelter.Manga.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(50);

                    b.Property<int>("TypeId")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("mangas");
                });

            modelBuilder.Entity("OtakuShelter.Manga.MangaTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnName("tag_id");

                    b.Property<int>("MangaId")
                        .HasColumnName("manga_id");

                    b.HasKey("TagId", "MangaId");

                    b.HasIndex("MangaId");

                    b.ToTable("manga_tags");
                });

            modelBuilder.Entity("OtakuShelter.Manga.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("ChapterId")
                        .HasColumnName("chapter_id");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnName("page_url")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("pages");
                });

            modelBuilder.Entity("OtakuShelter.Manga.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("OtakuShelter.Manga.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("types");
                });

            modelBuilder.Entity("OtakuShelter.Manga.Chapter", b =>
                {
                    b.HasOne("OtakuShelter.Manga.Manga", "Manga")
                        .WithMany("Chapters")
                        .HasForeignKey("MangaId")
                        .HasConstraintName("FK_manga_chapters")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OtakuShelter.Manga.Manga", b =>
                {
                    b.HasOne("OtakuShelter.Manga.Type", "Type")
                        .WithMany("Mangas")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_type_mangas")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OtakuShelter.Manga.MangaTag", b =>
                {
                    b.HasOne("OtakuShelter.Manga.Manga", "Manga")
                        .WithMany("MangaTags")
                        .HasForeignKey("MangaId")
                        .HasConstraintName("FK_manga_mangatags")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OtakuShelter.Manga.Tag", "Tag")
                        .WithMany("MangaTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("FK_tag_mangatags")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OtakuShelter.Manga.Page", b =>
                {
                    b.HasOne("OtakuShelter.Manga.Chapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .HasConstraintName("FK_chapter_pages")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
