- hosts: services
  
  vars:
    ansible_become: true
    ansible_become_pass: root
    ansible_become_method: su
    ansible_user: ansible
    otakushelter_buildnumber: 2

  roles:
  - install-docker

  tasks:
  - name: mkdir artifacts
    file: path=/otakushelter/manga/artifacts/build_{{ otakushelter_buildnumber }} state=directory

  - name: copy a directory
    unarchive:
      src: ../../artifacts.tar
      dest: /otakushelter/manga/artifacts/build_{{ otakushelter_buildnumber }}
