---
- name: apt-get install
  apt: name={{ item }} state=latest
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common

- name: apt-key add
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600

- name: add-apt-repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: apt-get install docker-ce
  apt: name=docker-ce state=latest